os: linux
dist: xenial
language: c

git:
  depth: 3
  quiet: true
  submodules: false

cache:
  directories:
  - $HOME/build/pencil-code/pencil-code/samples/no-modules/src
  - $HOME/build/pencil-code/pencil-code/samples/most-modules/src

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install -y gfortran
  - sudo apt-get install -y libhdf5-openmpi-dev libopenmpi-dev openmpi-bin
  - sudo apt-get install -y python-matplotlib
  - gfortran --version

script:
  - source sourceme.sh
  - pc_auto-test --host-id travis-ci -t --max-level 1 --script-tests=python --auto-clean
