os: linux
dist: focal
language: c

git:
  depth: 3
  quiet: true
  submodules: false

cache:
  directories:
  - $HOME/build/pencil-code/pencil-code/samples/no-modules/src
  - $HOME/build/pencil-code/pencil-code/samples/most-modules/src
  - $HOME/build/pencil-code/pencil-code/samples/backwards-compatible/src
  - $HOME/build/pencil-code/pencil-code/samples/1d-tests/implicit_diffusion/src
  - $HOME/build/pencil-code/pencil-code/samples/2d-tests/chemistry_GrayScott/src
  - $HOME/build/pencil-code/pencil-code/samples/2d-tests/shearwave-dust-par/src
  - $HOME/build/pencil-code/pencil-code/samples/dust-vortex/src
  - $HOME/build/pencil-code/pencil-code/samples/damped_alfven_waves/src
  - $HOME/build/pencil-code/pencil-code/samples/corona/src

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install -y gfortran
  - sudo apt-get install -y libhdf5-openmpi-dev libopenmpi-dev openmpi-bin
  - sudo apt-get install -y python3-matplotlib
  - sudo apt-get install -y git-restore-mtime
  - gfortran --version
  - cd $HOME/build/pencil-code/pencil-code/ && git restore-mtime src/

script:
  - source sourceme.sh
  - pc_auto-test --host-id travis-ci -t --max-level 1 --script-tests=python --auto-clean
