os: linux
dist: xenial
language: c

git:
  depth: 3
  quiet: true
  submodules: false

addons:
  apt:
    sources:
    - gfortran
    - libhdf5-openmpi-dev
    - libopenmpi-dev
    - openmpi-bin
    - python-matplotlib

cache:
  directories:
  - $HOME/build/pencil-code/pencil-code/samples

before_install:
  - gfortran --version

script:
  - source sourceme.sh
  - pc_auto-test --host-id travis-ci -t --max-level 1 --script-tests=python --auto-clean
