"""
Plugin that allows Paraview to read Pencil-code snapshots
"""

import paraview.util.vtkAlgorithm as vtka
import pathlib
import pencil as pc
import numpy as np

@vtka.smproxy.reader(
	name="Pencil snapshot plugin",
	label="Reader for snapshots generated by the Pencil code",
	filename_patterns==["VAR*.h5","VAR*.dat"], #TODO: not sure if this should be a list or something else. Maybe it would be better to just allow to select the datadir
	file_description="Pencil snapshots"
	)
class PencilSnapReader(vtka.VTKPythonAlgorithmBase):
	"""
	Read snapshots generated by Pencil-code. All formats supported by Pencil's Python module are supported.
	"""
	def __init__(self):
		import uuid; print("starting",uuid.uuid1()) #debug
		
		self._sim = None
	
	@vtka.smproperty.stringvector(name="FileName")
	@vtka.smdomain.filelist()
	@vtka.smhint.filechooser #(extensions="pcd", file_description="pcd file") # TODO: decorator needed even if no args?
	def SetFileName(self, name):
		if self._sim.path != name:
			self._sim = pc.sim.Simulation(path=name, quiet=True)
			self.Modified()

	@vtka.smproperty.doublevector(
		name="TimestepValues",
		information_only="1",
		si_class="vtkSITimeStepsProperty",
		)
	def GetTimestepValues(self):
		varlist = self._sim.get_varlist()
		times = [self._sim.get_var_time(v) for v in varlist]
		return np.sort(times)

	@vtka.smproperty.dataarrayselection(name="Arrays")
	def GetDataArraySelection(self):
		raise NotImplementedError

	def RequestInformation(self, request, inInfoVec, outInfoVec):
		raise NotImplementedError

	def RequestData(self, request, inInfoVec, outInfoVec):
		raise NotImplementedError
